version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modbd_frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - pub_cache:/root/.pub-cache
    stdin_open: true
    tty: true

volumes:
  pub_cache: